name: variable_testing
on:
    push:
      branches: [ "yash" ]
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
          - name: Set Google Cloud Project
            run: |
                gcloud config set project ${{ secrets.Project_ID }}   
                echo "Project ID: ${{ secrets.Project_ID }}"     
          - name: Use Secret
            env:
              MY_ORG_SECRET: ${{ secrets.CICD_SECRET }}
            run: echo $MY_ORG_SECRET

          - name: Authenticate to Google Cloud
            uses: google-github-actions/auth@v1
            with:
                credentials_json: ${{ secrets.CICD_SECRET }} 
                project_id: ${{ secrets.CICD_SECRET }} 
