name: variable_testing
on:
  push:
    branches: [ "yash" ]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write GCP credentials to file
        run: echo "${{ secrets.CICD_SECRET }}" > ${{ runner.temp }}/gcloud.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.CICD_SECRET }}

      - name: Set Google Cloud Project
        run: |
          gcloud config set project ${{ secrets.Project_ID }}
          echo "Project ID: ${{ secrets.Project_ID }}"

      - name: Test GCloud Authentication
        run: gcloud auth list

      - name: Use Secret
        env:
          MY_ORG_SECRET: ${{ secrets.CICD_SECRET }}
        run: echo "Secret loaded successfully"
